//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOMESTAY_SH.Database_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnhHomestay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnhHomestay()
        {
            this.Homestays = new HashSet<Homestay>();
        }
    
        public string MaAnh { get; set; }
        public string MaHomestay { get; set; }
        public string AnhChinh { get; set; }
        public string AnhPhu1 { get; set; }
        public string AnhPhu2 { get; set; }
        public string AnhPhu3 { get; set; }
        public string AnhPhu4 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Homestay> Homestays { get; set; }
    }
}
