//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOMESTAY_SH.Database_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoDuong
    {
        public string MaBaoDuong { get; set; }
        public string MaHomestay { get; set; }
        public Nullable<System.DateTime> NgayBaoDuong { get; set; }
        public Nullable<System.DateTime> NgayHoanThanh { get; set; }
        public Nullable<double> ChiPhi { get; set; }
        public string MoTaCongViec { get; set; }
        public string TrangThai { get; set; }
    
        public virtual Homestay Homestay { get; set; }
    }
}
