//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOMESTAY_SH.Database_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDichVuDatHomestay
    {
        public string MaChiTietDichVuDatHomestay { get; set; }
        public string MaDatHomestay { get; set; }
        public string MaDichVu { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> TongTienDichVu { get; set; }
    
        public virtual ChiTietDatHomestay ChiTietDatHomestay { get; set; }
        public virtual DichVu DichVu { get; set; }
    }
}
