//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOMESTAY_SH.Database_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDatHomestay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietDatHomestay()
        {
            this.ChiTietDichVuDatHomestays = new HashSet<ChiTietDichVuDatHomestay>();
            this.ThanhToans = new HashSet<ThanhToan>();
        }
    
        public string MaDatHomestay { get; set; }
        public string MaKhachHang { get; set; }
        public string MaHomestay { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<int> SoLuongKhach { get; set; }
        public Nullable<double> TongTien { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual Homestay Homestay { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDichVuDatHomestay> ChiTietDichVuDatHomestays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhToan> ThanhToans { get; set; }
    }
}
