//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOMESTAY_SH.Database_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public string MaDanhGia { get; set; }
        public string MaKhachHang { get; set; }
        public string MaHomestay { get; set; }
        public Nullable<double> DiemDanhGia { get; set; }
        public string NoiDungDanhGia { get; set; }
    
        public virtual Homestay Homestay { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
