//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOMESTAY_SH.Database_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Homestay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Homestay()
        {
            this.BaoDuongs = new HashSet<BaoDuong>();
            this.ChiTietDatHomestays = new HashSet<ChiTietDatHomestay>();
            this.DanhGias = new HashSet<DanhGia>();
        }
    
        public string MaHomestay { get; set; }
        public string TenHomestay { get; set; }
        public string MaKhuVuc { get; set; }
        public string MaAnh { get; set; }
        public string DiaChi { get; set; }
        public string MoTa { get; set; }
        public double GiaThue { get; set; }
        public int SoLuongKhach { get; set; }
        public string DienTich { get; set; }
        public string TienNghi { get; set; }
        public Nullable<System.DateTime> NgayXayDung { get; set; }
        public string MaNhanVienTruc { get; set; }
        public string TrangThai { get; set; }
        public Nullable<double> DiemTrungBinh { get; set; }
    
        public virtual AnhHomestay AnhHomestay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaoDuong> BaoDuongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDatHomestay> ChiTietDatHomestays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual KhuVuc KhuVuc { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
